name: at_proj
description: A simple login/sign-up with MongoDB example

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.17.5
  flutter_rating_bar: ^4.0.1
  firebase_storage: ^11.6.5
  lottie: ^2.6.0
  image_picker: ^1.1.0
  charts_flutter: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: True
  assets:
    - assets/download.jpeg
    - assets/download.jpg
    - assets/Widget, lockscreen.jpg
    - assets/Book lover Wallpaper.jpg
    - assets/book1.jpeg
    - assets/book2.jpeg
    - assets/book3.jpeg
    - assets/book4.jpeg
    - assets/book5.jpeg


