name: at_proj
description: A simple login/sign-up with MongoDB example

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.5.0
  flutter_rating_bar: ^4.0.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/download.jpeg
    - assets/download.jpg
    - assets/Widget, lockscreen.jpg
    - assets/Book lover Wallpaper.jpg
    - assets/Animation - 1744914550036.json
