// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCakN0rLcoFng6DSZkc_jz7g4DtQsL9cdA',
    appId: '1:986884770349:web:33b1e5b0285b35912f46a4',
    messagingSenderId: '986884770349',
    projectId: 'book-tracker1',
    authDomain: 'book-tracker1.firebaseapp.com',
    storageBucket: 'book-tracker1.firebasestorage.app',
    measurementId: 'G-TJR92YDZ8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Mb8MVwr-xy590jBYNYq6aSpH4lYW3VA',
    appId: '1:986884770349:android:91e57420eb61c1502f46a4',
    messagingSenderId: '986884770349',
    projectId: 'book-tracker1',
    storageBucket: 'book-tracker1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs_wuDoim1KYm6jIfZ6FoNRlTBjXWO1zA',
    appId: '1:986884770349:ios:6ef072ccce041ad22f46a4',
    messagingSenderId: '986884770349',
    projectId: 'book-tracker1',
    storageBucket: 'book-tracker1.firebasestorage.app',
    iosBundleId: 'com.example.atProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs_wuDoim1KYm6jIfZ6FoNRlTBjXWO1zA',
    appId: '1:986884770349:ios:6ef072ccce041ad22f46a4',
    messagingSenderId: '986884770349',
    projectId: 'book-tracker1',
    storageBucket: 'book-tracker1.firebasestorage.app',
    iosBundleId: 'com.example.atProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCakN0rLcoFng6DSZkc_jz7g4DtQsL9cdA',
    appId: '1:986884770349:web:6aebd636b61c57192f46a4',
    messagingSenderId: '986884770349',
    projectId: 'book-tracker1',
    authDomain: 'book-tracker1.firebaseapp.com',
    storageBucket: 'book-tracker1.firebasestorage.app',
    measurementId: 'G-1JG1TK29X0',
  );

}